### PR TITLE
Update bittensor to 6.11.0 in staging

### LINKED ISSUE #182: Staging branch should use bittensor 6.11.0, not 6.9.3
Since [`staging` branch is used for the testnet](https://discord.com/channels/799672011265015819/1182096085636878406/1233222527623368755),

> staging branch is for testnet miners/validators

... it [should be using the bittensor 6.11.0](https://discord.com/channels/799672011265015819/830075335084474390/1232796078294958151)

> NOTE: All testnet folks must update to bittensor==6.11.0 in order to use the testnet now.

.. and not the 6.9.3 which is [currently listed in the requirements](https://github.com/ifrit98/storage-subnet/blob/990a7a94368310110e75dedb4da1e4e7d3a17e37/requirements.txt#L1).

> bittensor==6.9.3

Currently the storage-subnet will uninstall 6.11.0 and install 6.9.3, which is wrong as reported by user on discord [here](https://discord.com/channels/799672011265015819/1182096085636878406/1233708801299976192), which is trivial to reproduce by upgrading bittensor to latest `python3 -m pip install --upgrade bittensor` followed by `python3 -m pip install -e .` in this repo:

image

### PR DESCRIPTION
**Pull request by birkskyum**
Closes #182

### CODE REVIEW

**Review by ifrit98 — APPROVED** [review]
Thanks!

**Comment by ifrit98** [comment]
This will require more changes as `loguru` is no longer used in bittensor as the default logger and we extend it in FileTAO

**Comment by birkskyum** [comment]
Does bittensor introduce breaking changes in a minor release? Odd

**Comment by birkskyum** [comment]
Glad to see this resolved in the 3.0.0. Thanks!

**Pull request closed without merging**
